package BuyStockUseCase;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class BuyStockGUI extends JFrame implements iBuyStockGUI {
    /**
     * GUI where the user can purchase stocks
     */
    private JButton buyButton;
    private JTextField quantityField;
    private JLabel buyStockLabel;
    private JLabel quantityLabel;
    private JLabel responseLabel;
    private JLabel symbolLabel;
    private JButton goBackButton;
    private JPanel mainPanel;

    public BuyStockGUI(String symbol) {
        super();

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(mainPanel);
        this.symbolLabel.setText(symbol);
        this.responseLabel.setText("");
        this.pack();
        this.setVisible(true);
    }

    @Override
    public void addBuyAction(Runnable onLogin) {
        buyButton.addActionListener(e -> onLogin.run());
    }

    @Override
    public void addGoBackAction(Runnable onBack) {
        goBackButton.addActionListener(e -> onBack.run());
    }

    @Override
    public void close() {
        dispose();
    }

    @Override
    public void displayBalanceFailure() {
        this.responseLabel.setText("Insufficient balance.");
    }

    @Override
    public void displayConnectionFailure() {
        this.responseLabel.setText("There was a problem connecting to the stock price service.");
    }

    @Override
    public void displayInvalidInputFailure() {
        this.responseLabel.setText("Please enter a positive integer.");
    }

    @Override
    public void displaySuccess() {
        this.responseLabel.setText("Purchase successful!");
    }

    @Override
    public String getSymbol() {
        return this.symbolLabel.getText();
    }

    @Override
    public int getQuantity() throws NumberFormatException {
        return Integer.parseInt(this.quantityField.getText());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 5, new Insets(0, 0, 0, 0), -1, -1));
        buyButton = new JButton();
        buyButton.setText("Buy");
        mainPanel.add(buyButton, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        quantityField = new JTextField();
        quantityField.setText("");
        mainPanel.add(quantityField, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        quantityLabel = new JLabel();
        quantityLabel.setText("Quantity:");
        mainPanel.add(quantityLabel, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        responseLabel = new JLabel();
        responseLabel.setText("");
        mainPanel.add(responseLabel, new GridConstraints(4, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        symbolLabel = new JLabel();
        symbolLabel.setText("_");
        mainPanel.add(symbolLabel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buyStockLabel = new JLabel();
        buyStockLabel.setText("Buy Stock:");
        mainPanel.add(buyStockLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        goBackButton = new JButton();
        goBackButton.setText("Go Back");
        mainPanel.add(goBackButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(91, 30), null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}